services:
  - type: web
    name: evolution-api
    env: node
    plan: starter
    branch: main
    autoDeploy: true
    buildCommand: npm ci && export DATABASE_PROVIDER=postgresql && npm run db:generate && npm run db:deploy && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /
    envVars:
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: AUTHENTICATION_API_KEY
        sync: false
      - key: DATABASE_CONNECTION_URI
        sync: false
      - key: CORS_ORIGIN
        value: "*"
